apiVersion: v1
kind: Service
metadata:
  name: consul-0-svc
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector:
    statefulset.kubernetes.io/pod-name: consul-0
  ports:
  - protocol: TCP
    port: 8500
    targetPort: 8500