apiVersion: v1
kind: Service
metadata:
  name: vault-svc
  labels:
    app: vault-svc
spec:
  type: ClusterIP
  ports:
    - port: 8200
      targetPort: 8200
      protocol: TCP
      name: vault
  selector:
    app: vault